#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

do_mount_root() {
	mount_root
	boot_run_hook preinit_mount_root
	[ -f /sysupgrade.tgz ] && {
		echo "- config restore -"
		cd /
		tar xzf /sysupgrade.tgz

        local luci_guide="/usr/lib/lua/luci/firstlogin"
        [ -f $luci_guide ] && rm -f $luci_guide
	}

	#zhangzf 20160527 add
	[ -f /lib/upgrade/nand.sh ] && {
		. /lib/upgrade/nand.sh
		nand_kt_restore_config
	}
}

[ "$INITRAMFS" = "1" ] || boot_hook_add preinit_main do_mount_root
